### ISSUE TITLE
Query on Keywords

### ISSUE THREAD

**Issue by rsob2005** [mauricekoster/gherkin2robotframework#6]
Hi, when I run the gherkin2robotframework command on my feature and the keywords are generated - which are not implemented - how is this working?  

The step definitions that I currently have for selenium ( which work for by BBD behave runner ) are not considered when gherkin2robotframework is building its two robot files?

So I am just trying to understand what I should do for all the steps that are considered 'not implemented keywords'  

Thanks a lot - like your work!
Richard

**Comment by mauricekoster** [comment]
Hi,
When a feature is generated the first time, the step definitions has no action to do. You need to place the keywords here to actually do the actions intented by the step.

If you regenerate the feature, the step definition will NOT be replaced. Instead missing steps will be outputed to the console,
